[package]
name = "rogue-tiny"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "~0.8"
bevy_roguelike_plugin = { path = "bevy_roguelike_plugin" }
# TODO: should be in debug only
bevy-inspector-egui = "~0.9"

[dependencies.bevy]
version = "~0.6"
default-features = false
features = ["render", "bevy_winit", "png"]


[workspace]
members = ["bevy_roguelike_plugin"]
