[package]
name = "vec_walk_dir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
walkdir = "2"
proc-macro2 = "1"
syn = "1"
quote = "1"
